replicaCount: 3

image:
  repository: nginx
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: pos-system-serviceaccount
  automount: true

secrets: # Store-specific secrets
  name: pos-system-secret-store2 # Kubernetes Secret for Store 2
  values:
    - name: DB_PASSWORD
      key: db-password
    - name: API_KEY
      key: api-key

env: # Store-specific environment variable
  STORE_ID: store2

ingress:
  enabled: false # Change to true if you want ingress enabled
  className: nginx
  annotations: {}
  hosts:
    - host: store2.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false # Set to true to enable HPA
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
