replicaCount: 3

image:
  repository: nginx
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: pos-system-serviceaccount
  automount: true

secrets: # Adding Secrets Integration
  enabled: true
  name: pos-system-secret # Kubernetes Secret name
  values:
    - name: DB_PASSWORD
      key: db-password
    - name: API_KEY
      key: api-key

ingress:
  enabled: false # Change to true if you want ingress enabled
  className: nginx
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false # Set to true to enable HPA
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env: # Adding environment variables for store-specific configuration
  STORE_ID: store1 # Default store ID

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
