apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pos
  labels:
    app: {{ .Release.Name }}-pos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pos
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pos
    spec:
      containers:
      - name: pos-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pos-secrets
              key: api-key
