apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-system-store2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SpelmanDevops/retail-store.git
    path: helm/pos-system
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-store2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: store2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
